#############################################################################
# Makefile for building: ns-3-generator
# Generated by qmake (2.01a) (Qt 4.4.3) on: mar. mai 19 17:13:29 2009
# Project:  ns-3-generator.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile ns-3-generator.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Ikern -Igui -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		qrc_dragwidget.cpp \
		gui/Configuration.cpp \
		gui/DragWidget.cpp \
		gui/MainWindow.cpp \
		kern/Application.cpp \
		kern/Bridge.cpp \
		kern/Emu.cpp \
		kern/Equipement.cpp \
		kern/Generator.cpp \
		kern/Hub.cpp \
		kern/Link.cpp \
		kern/Ping.cpp \
		kern/PointToPoint.cpp \
		kern/Tap.cpp \
		kern/TcpLargeTransfer.cpp \
		kern/UdpEcho.cpp \
		kern/Wifi.cpp moc_Configuration.cpp \
		moc_MainWindow.cpp \
		qrc_DragWidget.cpp
OBJECTS       = main.o \
		qrc_dragwidget.o \
		Configuration.o \
		DragWidget.o \
		MainWindow.o \
		Application.o \
		Bridge.o \
		Emu.o \
		Equipement.o \
		Generator.o \
		Hub.o \
		Link.o \
		Ping.o \
		PointToPoint.o \
		Tap.o \
		TcpLargeTransfer.o \
		UdpEcho.o \
		Wifi.o \
		moc_Configuration.o \
		moc_MainWindow.o \
		qrc_DragWidget.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		ns-3-generator.pro
QMAKE_TARGET  = ns-3-generator
DESTDIR       = 
TARGET        = ns-3-generator

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ns-3-generator.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile ns-3-generator.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile ns-3-generator.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ns-3-generator1.0.0 || $(MKDIR) .tmp/ns-3-generator1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ns-3-generator1.0.0/ && $(COPY_FILE) --parents gui/Configuration.h gui/DragWidget.h gui/MainWindow.h kern/Application.h kern/Bridge.h kern/Emu.h kern/Equipement.h kern/Generator.h kern/Hub.h kern/Link.h kern/Ping.h kern/PointToPoint.h kern/Tap.h kern/TcpLargeTransfer.h kern/UdpEcho.h kern/Wifi.h .tmp/ns-3-generator1.0.0/ && $(COPY_FILE) --parents gui/DragWidget.qrc .tmp/ns-3-generator1.0.0/ && $(COPY_FILE) --parents main.cpp qrc_dragwidget.cpp gui/Configuration.cpp gui/DragWidget.cpp gui/MainWindow.cpp kern/Application.cpp kern/Bridge.cpp kern/Emu.cpp kern/Equipement.cpp kern/Generator.cpp kern/Hub.cpp kern/Link.cpp kern/Ping.cpp kern/PointToPoint.cpp kern/Tap.cpp kern/TcpLargeTransfer.cpp kern/UdpEcho.cpp kern/Wifi.cpp .tmp/ns-3-generator1.0.0/ && (cd `dirname .tmp/ns-3-generator1.0.0` && $(TAR) ns-3-generator1.0.0.tar ns-3-generator1.0.0 && $(COMPRESS) ns-3-generator1.0.0.tar) && $(MOVE) `dirname .tmp/ns-3-generator1.0.0`/ns-3-generator1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ns-3-generator1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_Configuration.cpp moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Configuration.cpp moc_MainWindow.cpp
moc_Configuration.cpp: gui/Configuration.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) gui/Configuration.h -o moc_Configuration.cpp

moc_MainWindow.cpp: gui/DragWidget.h \
		gui/Configuration.h \
		gui/MainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) gui/MainWindow.h -o moc_MainWindow.cpp

compiler_rcc_make_all: qrc_DragWidget.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_DragWidget.cpp
qrc_DragWidget.cpp: gui/DragWidget.qrc \
		gui/Ico/StationWifi.png \
		gui/Ico/PC-Emu.png \
		gui/Ico/AP-Wifi.png \
		gui/Ico/Del.png \
		gui/Ico/PC.png \
		gui/Ico/PC-Tap.png
	/usr/bin/rcc -name DragWidget gui/DragWidget.qrc -o qrc_DragWidget.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp kern/Generator.h \
		kern/Equipement.h \
		kern/Link.h \
		kern/Application.h \
		gui/MainWindow.h \
		gui/DragWidget.h \
		gui/Configuration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_dragwidget.o: qrc_dragwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_dragwidget.o qrc_dragwidget.cpp

Configuration.o: gui/Configuration.cpp gui/Configuration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Configuration.o gui/Configuration.cpp

DragWidget.o: gui/DragWidget.cpp gui/DragWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DragWidget.o gui/DragWidget.cpp

MainWindow.o: gui/MainWindow.cpp gui/DragWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o gui/MainWindow.cpp

Application.o: kern/Application.cpp kern/Application.h \
		kern/Generator.h \
		kern/Equipement.h \
		kern/Link.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Application.o kern/Application.cpp

Bridge.o: kern/Bridge.cpp kern/Bridge.h \
		kern/Link.h \
		kern/Generator.h \
		kern/Equipement.h \
		kern/Application.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bridge.o kern/Bridge.cpp

Emu.o: kern/Emu.cpp kern/Emu.h \
		kern/Link.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Emu.o kern/Emu.cpp

Equipement.o: kern/Equipement.cpp kern/Equipement.h \
		kern/Generator.h \
		kern/Link.h \
		kern/Application.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Equipement.o kern/Equipement.cpp

Generator.o: kern/Generator.cpp kern/Generator.h \
		kern/Equipement.h \
		kern/Link.h \
		kern/Application.h \
		kern/Hub.h \
		kern/PointToPoint.h \
		kern/Bridge.h \
		kern/Wifi.h \
		kern/Ping.h \
		kern/UdpEcho.h \
		kern/TcpLargeTransfer.h \
		kern/Tap.h \
		kern/Emu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Generator.o kern/Generator.cpp

Hub.o: kern/Hub.cpp kern/Hub.h \
		kern/Link.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Hub.o kern/Hub.cpp

Link.o: kern/Link.cpp kern/Link.h \
		kern/Generator.h \
		kern/Equipement.h \
		kern/Application.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Link.o kern/Link.cpp

Ping.o: kern/Ping.cpp kern/Ping.h \
		kern/Application.h \
		kern/Generator.h \
		kern/Equipement.h \
		kern/Link.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Ping.o kern/Ping.cpp

PointToPoint.o: kern/PointToPoint.cpp kern/PointToPoint.h \
		kern/Link.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PointToPoint.o kern/PointToPoint.cpp

Tap.o: kern/Tap.cpp kern/Tap.h \
		kern/Link.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Tap.o kern/Tap.cpp

TcpLargeTransfer.o: kern/TcpLargeTransfer.cpp kern/TcpLargeTransfer.h \
		kern/Application.h \
		kern/Generator.h \
		kern/Equipement.h \
		kern/Link.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TcpLargeTransfer.o kern/TcpLargeTransfer.cpp

UdpEcho.o: kern/UdpEcho.cpp kern/UdpEcho.h \
		kern/Application.h \
		kern/Generator.h \
		kern/Equipement.h \
		kern/Link.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UdpEcho.o kern/UdpEcho.cpp

Wifi.o: kern/Wifi.cpp kern/Wifi.h \
		kern/Link.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Wifi.o kern/Wifi.cpp

moc_Configuration.o: moc_Configuration.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Configuration.o moc_Configuration.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

qrc_DragWidget.o: qrc_DragWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_DragWidget.o qrc_DragWidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

